DESC EMPLOYEES_COPY;

SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES_COPY;

-SENARYO-1
- 101 VE 102 SICIL NUMARALI ÇALISANLARIN MAAÞINI 400$ DÜÞÜRÜP KOMÝSSÝONLARI SIFIRLA.

UPDATE EMPLOYEES_COPY SET SALARY= SALARY-400, COMMISSION_PCT=NULL WHERE EMPLOYEE_ID IN (101,102);

-SENARYO-2
-100 NOLU BÖLÜMDE ÇALIÞANLARIN MAAÞINA ZAM YAPMADAN ÖNCEKÝ HALÝNE UPDATE EDELÝM
-BUNUN ÝÇÝN BAÞKA BÝ TABLODAN EMPLOYEES DEÐERÝ
-DÝÐER TABLOYA EMPLOYEES_COPY DEÐERÝNÝ UPDATE EDECEÐÝZ

SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES_COPY WHERE DEPARTMENT_ID = 90;
 
UPDATE EMPLOYEES_COPY A SET A.SALARY=(SELECT B.SALARY FROM EMPLOYEES B WHERE A.EMPLOYEE_ID = B.EMPLOYEE_ID)
WHERE A.DEPARTMENT_ID=90;
Commit;