            -HÝERARCHICAL QUERIES (HÝYERARÞÝK SORGULAR)

1) CONNECT BY PRIOR ÖRNEÐÝ (ÇALIÞANLAR ÝLE YÖNETÝCÝLER ARASINDAKÝ HÝYERARÞÝK ÝLÝÞKÝ)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

2) LEVEL ÖRNEÐÝ (ÇALIÞANLAR ÝLE YÖNETÝCÝLER ARASINDAKÝ HÝYERARÞÝK ÝLÝÞKÝ - SEVÝYE NO)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID, LEVEL FROM EMPLOYEES CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

3) START WITH ÖRNEÐÝ (HÝYERARÞÝÐÝ BELÝRLÝ BÝR NOKTADAN BAÞLATABÝLÝRÝZ. AYRICA SUBLINOS ANAHTAR KELÝMESÝNÝ KULLANARAK HÝYERARÞÝK SIRALAMA YAPABÝLÝRÝZ)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID, LEVEL FROM EMPLOYEES START WITH EMPLOYEE_ID=100 CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID ORDER SIBLINGS BY LAST_NAME;

4) CONNECT_BY_ROOT - SYS_CONNECT_BY_PATH ÖRNEÐÝ(HER ÇALIÞANIN HÝYERARÞÝDE BAÐLI OLDUÐU ÜST BÝRÝM VE SEVÝYESÝ)

- LEVEL 1 => LEVEL 2 => LEVEL 3  (ÇIKTI ELDE EDÝCEZ)
- DEDE => BABA => TORUN

SELECT LAST_NAME "ÇALIÞAN KÝÞÝ",CONNECT_BY_ROOT LAST_NAME "YÖNETÝCÝ", LEVEL -1, SYS_CONNECT_BY_PATH(LAST_NAME,'=>') FROM EMPLOYEES CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;
