1)TÜM KOLONLARIN SORGULANMASI
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID ASC, FIRST_NAME DESC ;

2)TABLODAKÝ BELÝRLÝ KOLONLARIN SORGULANMASI
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES ORDER BY MANAGER_ID ASC;
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES ORDER BY 2 ASC;

3)KOLONLARIN BAÞLIKLARININ DEÐÝÞTÝRÝLMESÝ (TEK KELÝMEDEN OLUSAN BAÞLIKLAR)
SELECT MANAGER_ID MGR, FIRST_NAME ADI, LAST_NAME SOYADI, EMAIL EMAÝL FROM EMPLOYEES;

4)KOLONLARIN BAÞLIKLARININ DEÐÝÞTÝRÝLMESÝ (BÝRDEN FAZLA KELÝMEDEN OLUSAN BAÞLIKLAR)
SELECT MANAGER_ID "MÜDÜR NO", FIRST_NAME "ÝLK ADI", LAST_NAME "SON ADI", EMAIL "E MAÝL" FROM EMPLOYEES;

5)WHERE CONDITIONS (ÖRNEK: 90 NOLU BÖLÜMDE ÇALIÞANLARIN LÝSTESÝ)
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=90;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=90 ORDER BY SALARY ASC;

6)WHERE CONDITIONS (ÖRNEK: 100 NOLU BÖLÜMDE ÇALIÞANLARIN LÝSTESÝ)
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=100;

7)WHERE CONDITIONS ( ÖPRNEK: HEM 100 HEMDE 90 NOLU BÖLÜMDE ÇALIÞANLARIN LÝSTESÝ)
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (90,100);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 OR DEPARTMENT_ID = 100; 

8)SOYÝSMÝ (LAST_NAME) M ÝLE BAÞLAYAN ÇALIÞANLAR.
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'M%';

9)SOYÝSMÝNÝN ÝÇÝNDE MA GEÇEN KULLANICILAR
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%ma%';

10)SOYÝSMÝNDE 2.KARAKTERÝ A OLAN VE 4.KARAKTERÝ E OLAN ÇALIÞANLAR
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '_a_e%';

11)MAAÞI (SALARY) 10.000 ÜZERÝNDE OLUP KOMÝSYON ORANI BOÞ OLMAYANLAR
SELECT * FROM EMPLOYEES WHERE SALARY >10000 and COMMISSION_PCT ýs not null;