- ROLES

CREATE ROLE R_SELUPT;

CREATE ROLE R_INSDEL;

GRANT SELECT, UPDATE ON REGIONS TO R_SELUPT;

GRANT INSERT, DELETE ON REGIONS TO R_INSDEL;

GRANT R_SELUPT TO ALII;
GRANT R_INSDEL TO CELEBI;

REVOKE UPDATE ON REGIONS FROM R_SELUPT;