
--NVL(A,B)

SELECT FIRST_NAME, COMMISSION_PCT,
NVL(COMMISSION_PCT,0) 
FROM EMPLOYEES;

--NVL2(P1,P2,P3)

SELECT FIRST_NAME, SALARY, COMMISSION_PCT,
NVL2(COMMISSION_PCT,SALARY*(1+COMMISSION_PCT),SALARY)
FROM EMPLOYEES;

--NULLIF(A,B)

SELECT FIRST_NAME, SALARY, COMMISSION_PCT,
NULLIF(SALARY, SALARY - NVL(COMMISSION_PCT,0))
FROM EMPLOYEES;

--GREATEST / LEAST

SELECT GREATEST(1,2,3,5,-4,11,15,5,6,11)FROM DUAL;
SELECT GREATEST('ALÝ', 'AYSE','FATMA','ZEYNEP')FROM DUAL; 
SELECT LEAST('ALÝ', 'AYSE','FATMA','ZEYNEP')FROM DUAL; 

--DECODE

SELECT LAST_NAME,DEPARTMENT_ID, DECODE(DEPARTMENT_ID,10,'MUHASEBE',20, 'ARAÞTIRMA','DÝÐER') FROM EMPLOYEES ORDER BY 2;

-- CASE

SELECT LAST_NAME,DEPARTMENT_ID, CASE DEPARTMENT_ID WHEN 10 THEN 'MUHASEBE' WHEN 20 THEN 'ARAÞTIRMA' ELSE 'DÝÐER' end as DEPARTMENT FROM EMPLOYEES ORDER BY 2;

-- UID / USER

SELECT UID ,USER FROM DUAL;

-- SYS_CONTEXT

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS USERNAME,
SYS_CONTEXT('USERENV', 'ISDBA') ISDBA,
SYS_CONTEXT('USERENV', 'HOST') HOST,
SYS_CONTEXT('USERENV', 'INSTANCE')INSTANCE,
SYS_CONTEXT('USERENV', 'IP_ADDRESS')IP,
SYS_CONTEXT('USERENV', 'DB_NAME')DBNAME
FROM DUAL;