
-- CURRENT_DATE / SYSDEATE 

SELECT CURRENT_DATE, SYSDATE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

ALTER SESSION SET TIME_ZONE = '+2:0';

SELECT SYSTIMESTAMP FROM DUAL;

-- TARÝH FORMATLARI

SELECT SYSDATE,
    TO_CHAR(SYSDATE,'D') HAFTANINKAÇINCIGÜNÜ,
    TO_CHAR(SYSDATE,'DD') AYINKAÇINCIGÜNÜ,
    TO_CHAR(SYSDATE,'DDD') YILINKAÇINCIGÜNÜ,
    TO_CHAR(SYSDATE,'DAY') GÜNÝSMÝ,
    TO_CHAR(SYSDATE,'DY') GÜNÝSMÝ,
    TO_CHAR(SYSDATE,'W') AYINKAÇINCIHAFTASI,
    TO_CHAR(SYSDATE,'WW') YILINKAÇINCIHAFTASI,
    TO_CHAR(SYSDATE,'MM') AYNO,
    TO_CHAR(SYSDATE,'MON') AYÝSMÝ,
    TO_CHAR(SYSDATE,'YYYY') YIL
FROM DUAL;