
SELECT DEPARTMENT_ID, 
       ROUND(AVG(SALARY),2),
       MAX(SALARY),
       MIN(SALARY),
       SUM(SALARY),
       COUNT(SALARY),
       STDDEV(SALARY),
       VARIANCE(SALARY)
        
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID  
HAVING COUNT(SALARY)>1
ORDER BY DEPARTMENT_ID;

--------------------------------------------------------------------------------

--ÖRNEK: 1)ÇALISANIN ADI, MAAÞI, KOMULATIF TOPLAM(ÇALIÞANLARIN ADINA GÖRE SIRALANSIN)
    
SELECT FIRST_NAME, SALARY,
SUM(SALARY) OVER(ORDER BY FIRST_NAME) AS TOPLAMMAAÞ
FROM EMPLOYEES
GROUP BY FIRST_NAME,SALARY;

  -- 2)ÇALIÞANIN ADI, MAAÞI, BÖLÜMÜ, KOMULATIF TOPLAM (BÖLÜME GÖRE GRUPLA,MAAÞA GÖRE SIRALA)
      
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID,
SUM(SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY)
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;      