-- INNER JOIN ( ANSI FORMATINDA)

/*

LAST NAME           DEPARTMENT_ID           DEPARTMENT_NAME         CITY
__________          _____________           _______________         ____

*/

SELECT
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    L.CITY
    
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
;



SELECT 
    E.FIRST_NAME,
    E.JOB_ID,    
    E.DEPARTMENT_ID,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME,
    D.LOCATION_ID,
    L.STREET_ADDRESS,
    L.COUNTRY_ID,
    C.COUNTRY_NAME

FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J ON J.JOB_ID = E.JOB_ID
INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L. COUNTRY_ID;





