-- RIGHT JOIN (GELENEKSEL FORMAT)

/*

DEPARTMENT_ID       DEPARTMENT_NAME     EMPLOYEE_ID     LAST_NAME       SALARY
_____________       _______________     ___________     _________       ______

DEPARTMENT_ID VE DEPARTMENT_NAME                (DEPARTMENT TABLOSUNDA)
EMPLOYEE_ID, LAST_NAME VE SALARY                (EPLOYEES TABLOSUNDA)

*/

SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    E.LAST_NAME,
    E.SALARY
      
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID(+);