-- LEFT JOIN (ANSI FORMAT)

/*

REGION_ID       REGION_NAME     COUNTRY_ID      COUNTRY_NAME        CITY
_________       ___________     __________      ____________        ____


REGION_ID VE REGION_NAME        (REGION TABLOSUNDA)
COUNTRY_ID VE COUNTRY_NAME      (COUNTRIES TABLOSUNDA)
CITY                            (LOCATIONS TABLOSUNDA)
*/

SELECT
    R.REGION_ID,
    R.REGION_NAME,
    C.COUNTRY_ID,
    C.COUNTRY_NAME,
    L.CITY

FROM REGIONS R
LEFT OUTER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
LEFT OUTER JOIN LOCATIONS L ON L.COUNTRY_ID = C.COUNTRY_ID;