-- LEFT JOIN (GELENEKSEL FORMAT)

/*

REGION_ID       REGION_NAME     COUNTRY_ID      COUNTRY_NAME        CITY
_________       ___________     __________      ____________        ____


REGION_ID VE REGION_NAME        (REGION TABLOSUNDA)
COUNTRY_ID VE COUNTRY_NAME      (COUNTRIES TABLOSUNDA)
CITY                            (LOCATIONS TABLOSUNDA)
*/

SELECT
    R.REGION_ID,
    R.REGION_NAME,
    C.COUNTRY_ID,
    C.COUNTRY_NAME,
    L.CITY

FROM REGIONS R,COUNTRIES C,LOCATIONS L
WHERE R.REGION_ID = C.REGION_ID(+) AND
C.COUNTRY_ID = L.COUNTRY_ID(+)
AND L.CITY IS NOT NULL
ORDER BY 1,3,5;