
SELECT *FROM DEPARTMENTS ORDER BY DEPARTMENT_ID ASC;

CREATE TABLE DEPT1 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 160;

CREATE TABLE DEPT2 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID >= 100;


SELECT * FROM DEPT1 ORDER BY DEPARTMENT_ID;

SELECT * FROM DEPT2 ORDER BY DEPARTMENT_ID;

----------------------------------------------------

SELECT * FROM DEPT1 UNION SELECT * FROM DEPT2;

SELECT * FROM DEPT1 UNION ALL SELECT * FROM DEPT2;


SELECT DEPARTMENT_NAME FROM DEPT1 UNION SELECT DEPARTMENT_NAME FROM DEPT2; 